[package]
name = "sshscan-core"
version = "0.3.1"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
xmltree = { version = "=0.10.3", default-features = false }
thiserror = { version = "~1.0.49", default-features = false }
build_html = { version = "~2.4.0", default-features = false }
chrono = { version = "~0.4.31", default-features = false, features = ["std", "clock", "unstable-locales"]}
arbitrary = { version = "1", optional = true, features = ["derive"] }
paste = { version = "~1.0.14", default-features = false }

[features]
default = []
fuzz = ["dep:arbitrary"]
