[package]
name = "sshscan-core"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
xmltree = { version = "=0.10.3", default-features = false }
thiserror = { version = "1.0.40", default-features = false }
build_html = { version = "2.4.0", default-features = false }
chrono = { version = "0.4.23", default-features = false, features = ["std", "clock", "unstable-locales"]}
