[package]
name = "sshscan-bin"
version = "0.3.2"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
sshscan-core = { path = "../sshscan-core" }
clap = { version = "4.2.1", default-features = false, features = ["std", "derive", "help", "usage", "suggestions", "error-context"] }
which = { version = "4.4.0", default-features = false }

[[bin]]
name = "sshscan"
path = "src/main.rs"
