[package]
name = "sshscan-bin"
version = "0.2.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
sshscan-core = { path = "../sshscan-core" }
clap = { version = "4.2.1", default-features = false, features = ["std", "derive", "help", "usage", "suggestions", "error-context"] }
which = { version = "4.4.0", default-features = false }
