[package]
name = "sshscan-bin"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
sshscan-core = { path = "../sshscan-core" }
clap = { version = "=4.0.32", default-features = false, features = ["std", "derive", "help", "usage", "suggestions", "error-context"] }